name: ${PROJECT_NAME}
networks:
  default:
    name: ${NETWORK_NAME}
    driver: bridge

services:
  server:
    container_name: ${PROJECT_NAME}-web
    extra_hosts:
      host.docker.internal: host-gateway  
    build:
      context: .
    restart: no
    ports: ["9080:80"]
    volumes:
      - ./htdocs/:/var/www/html
      - ./logs/:/var/www/logs
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
